name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: cainky
          template: terminal
          filename: metrics.terminal.svg
          base: header, activity, community, repositories, metadata
          config_timezone: America/Toronto
          
#           plugin_followup: yes
#           plugin_followup_archived: yes
#           plugin_followup_sections: repositories

#           plugin_isocalendar: yes
#           plugin_isocalendar_duration: full-year

          plugin_introduction: yes
          plugin_introduction_title: yes
          
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          plugin_habits: yes
          plugin_habits_charts: yes
          
          plugin_stars: yes
          plugin_stars_limit: 4
          
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_SECRETS }}
          plugin_music_mode: top
          plugin_music_top_type: tracks
          plugin_music_time_range: short
  
