name: Metrics
on:
  schedule: [{cron: "0 0 1 * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          template: classic
          filename: metrics.svg
          base: header, metadata, repositories
          config_timezone: America/Toronto
          user: cainky
          
          plugin_introduction: yes
          plugin_introduction_title: yes
          
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          plugin_stars: yes
          plugin_stars_limit: 4

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
#           plugin_music: yes
#           plugin_music_provider: spotify
#           plugin_music_token: ${{ secrets.SPOTIFY_SECRETS }}
#           plugin_music_mode: top
#           plugin_music_top_type: tracks
#           plugin_music_time_range: short
  
